### ISSUE TITLE
Missing settings button

### ISSUE THREAD

**Issue by Grommash9** [fastuuid/fastuuid#29]
Hey, @thedrow, I have tried to do that in some different ways, but it's looks like I need more access to the repo itself, because now I am not able to add/modify env variables and I should add a token form pypi what I have created, or I can send it to you by email and you will add it there.

Pypi supports the other way of AUTH and I have tested it, but it's support only Linux machines, so we should only use pypi token

From that topic:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository

I think I should be the owner of the repo to have settings? I am not sure

Please let me know what we can do about it. 

I have also created a tag and it's failed but nothing was published so maybe it's ok to delete it?

**Comment by thedrow** [comment]
It seems we need to be in an organization to allow you admin access to a repository.
I'll move this to an organization soon so you'll have admin access.

**Comment by Grommash9** [comment]
Sounds good to me, thanks! 

For push 0.9.1 I have initiated pipeline from my fork and it’s on pypi now. So while we don’t have that env variable in main repo i will be able to push updates from my fork.

**Comment by thedrow** [comment]
I moved the repo to an organization.

**Comment by thedrow** [comment]
@Grommash9 I sent you an invite.

**Comment by Grommash9** [comment]
Yes, thanks, I have added token now

We should be able to tag it from repo now and push to pypi

We also should match version from `Cargo.toml` and tag version with our current setup I think
